// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFTask.Models;

public partial class ITIDBContext : DbContext
{
    public ITIDBContext()
    {
    }

    public ITIDBContext(DbContextOptions<ITIDBContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Course> Courses { get; set; }

    public virtual DbSet<Topic> Topics { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see https://go.microsoft.com/fwlink/?LinkId=723263.
        => optionsBuilder.UseSqlServer("Data Source=DESKTOP-KII5RFR;Initial Catalog=ITI;Integrated Security=True;TrustServerCertificate=True");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Course>(entity =>
        {
            entity.HasKey(e => e.Crs_Id);

            entity.ToTable("Course");

            entity.Property(e => e.Crs_Id).ValueGeneratedNever();
            entity.Property(e => e.Crs_Name).HasMaxLength(50);

            entity.HasOne(d => d.Top).WithMany(p => p.Courses)
                .HasForeignKey(d => d.Top_Id)
                .HasConstraintName("FK_Course_Topic");
        });

        modelBuilder.Entity<Topic>(entity =>
        {
            entity.HasKey(e => e.Top_Id);

            entity.ToTable("Topic");

            entity.Property(e => e.Top_Id).ValueGeneratedNever();
            entity.Property(e => e.Top_Name).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}